types:
  - name: ingress
    cores: 0
    ram: 0
    ingress: true
    manageable: false
  - name: egress
    cores: 0
    ram: 0
    egress: true
    manageable: false
  - name: vFW
    cores: 2
    ram: 2
    manageable: true
  - name: vNAT
    cores: 2
    ram: 4
    manageable: true
  - name: vIDS
    cores: 2
    ram: 2
    manageable: true
  - name: vDPI
    cores: 2
    ram: 4
    manageable: true
